# Generated by Django 6.1 on 2026-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
